matrix:
  include:
    - os: windows
      language: sh
      python: 3.6
      name: Build on Python 3.6.8 in Windows
      env: PYVER="3.6.8" PYDIR="Python36" 
    - os: windows
      language: sh
      python: 3.7
      name: Build on Python 3.7.7 in Windows
      env: PYVER="3.7.7" PYDIR="Python37" 
    - os: windows
      language: sh
      python: 3.8
      name: Build on Python 3.8.3 in Windows
      env: PYVER="3.8.3" PYDIR="Python38" 

install:
  - curl -L https://aka.ms/nugetclidl -o nuget.exe
  - git clone https://github.com/3b1b/manim
  - ./nuget install pythonx86 -Version $PYVER -OutputDirectory python.$PYVER.x86
  - cd python.$PYVER.x86 && cp -r ../manim manim && cd ../
  - ./nuget install python -Version $PYVER -OutputDirectory python.$PYVER.x64
  - cd python.$PYVER.x64 && mv ../manim manim && cd ../
  - cmd.exe //c "RefreshEnv.cmd"
script:
  - cd python.$PYVER.x86
  - source ../python-x86.sh
  - dir
  - 7z a -t7z dist/build.$PYVER.x86.zip python.$PYVER.x86/*
  #- 7z a -t7z dist/build.$PYVER.x64.zip python.$PYVER.x64/*
cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

deploy:
  provider: releases
  file_glob: true
  api_key: $GITHUBOAUTHTOKEN
  file: dist/*.zip
  skip_cleanup: true
  draft: true