matrix:
  include:
    - os: windows
      language: sh
      python: 3.6
      name: Build on Python 3.6.8 in Windows
      env: PYVER="3.6.8" PYDIR="Python36" 
    - os: windows
      language: sh
      python: 3.7
      name: Build on Python 3.7.7 in Windows
      env: PYVER="3.7.7" PYDIR="Python37" 
    - os: windows
      language: sh
      python: 3.8
      name: Build on Python 3.8.3 in Windows
      env: PYVER="3.8.3" PYDIR="Python38" 

install:
  - choco install python --version=$PYVER
  - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
  - echo $PATH
  - cmd.exe //c "RefreshEnv.cmd"
script:
  - python -m venv manim-venv
  - cd manim-venv
  - source Scripts/activate
  - git clone https://github.com/3b1b/manim
  - cd manim
  - curl -sSL https://raw.githubusercontent.com/ManimCommunity/manim/master/scripts/pycairoinstall.py | python
  - python -m pip install -r requirements.txt
  - python -m pip install pyinstaller
  - pyinstaller --version
  - pyinstaller manim.py
  - 7z a -t7z dist/build$PYVER.zip dist/*.*
cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

deploy:
  provider: releases
  file_glob: true
  api_key: $GITHUBOAUTHTOKEN
  file: dist/*.zip
  skip_cleanup: true
  draft: true