name: Build Manim For Windows

on:
  push:
    branches: [ testing]

jobs:
  build_3_8_3:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make choco Package
      run: |
        cd "Choco Package"
        cd "manim"
        echo "Starting Chocolately"
        choco pack
        choco install --no-progress manim -source "'.;https://chocolatey.org/api/v2/'"
        echo "::set-env name=Path::$env:Path"
    - name: Test Generated Files
      run: |
        manim -h
        Invoke-WebRequest https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -O basic.py
        manim basic.py SquareToCircle
        choco uninstall -y manim
        manim -h
    - name: Upload Logs if failes
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
        
        
        
