name: Build Manim For Windows

on:
  push:
    branches: [ testing]

jobs:
  build_3_8_3:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-env
      uses: allenevans/set-env@v1.1.0
      with:
        PYVER: "3.8.3"
        PYDIR: Python38
    - name: Install dependencies
      run: |
        curl -L https://aka.ms/nugetclidl -o nuget.exe
        git clone https://github.com/ManimCommunity/manim.git
        nuget install pythonx86 -Version $env:PYVER -OutputDirectory python.$env:PYVER.x86
        cd python.$env:PYVER.x86 && cp -r ../manim manim && cd ../
        nuget install python -Version $env:PYVER -OutputDirectory python.$env:PYVER.x64
        cd python.$env:PYVER.x64 && mv ../manim manim && cd ../
        curl -L https://downloads.sourceforge.net/project/nsis/NSIS%203/3.05/nsis-3.05-setup.exe -o nsisinstaller.exe
        ./nsisinstaller.exe /S /D=C:\NSIS
        $env:Path += ";" + "C:\NSIS"
        echo "::set-env name=Path::$env:Path"
        cmd.exe //c "RefreshEnv.cmd"
    - name: Build 64 binaries
      run: |
        cd python.$env:PYVER.x64
        ../python-x64.bat
        dir manim/
        cd ../
        cd python.$env:PYVER.x86
        ../python-x86.bat
        dir manim/
        cd ../
        makensis makeexe64.nsi
        makensis makeexe86.nsi
        7z a -sfx build.$PYVER.x86.exe python.$PYVER.x86
        7z a -sfx build.$PYVER.x64.exe python.$PYVER.x64
    - name: Test Generated Files
      run: |
        ./Manim_1.0x64.exe /S /INSTDIR=D:\Manimx64
        Start-Sleep -s 300
        ./Manim_1.0x86.exe /S /INSTDIR=D:\Manimx86
        Start-Sleep -s 300
        Test-Path D:\Manimx64
        Test-Path D:\Manimx86
        dir D:\Manimx64
        dir D:\Manimx86
        echo $env:PATH
        Try {Invoke-WebRequest https://yihui.org/gh/tinytex/tools/install-windows.bat -O install_tinytex.bat}
        Catch {Invoke-WebRequest https://raw.githubusercontent.com/yihui/tinytex/master/tools/install-windows.bat -O install_tinytex.bat}
        Start-Process install_tinytex.bat -NoNewWindow -Wait
        $env:Path += ";" + $env:APPDATA + "\TinyTeX\bin\win32"
        tlmgr install standalone preview doublestroke ms setspace rsfs relsize ragged2e fundus-calligra microtype wasysym physics dvisvgm jknapltx wasy cm-super babel-english
        choco install --no-progress ffmpeg
        choco install --no-progress sox.portable
        echo $env:PATH
        $env:Path += ";" + "D:\Manimx64\python.3.8.3.x64\python.3.8.3\tools\Scripts"
        tree D:\Manimx64
        tree D:\Manimx86
        manim -h
        echo "::set-env name=Path::$env:Path"

    - name: Upload Release Asset x64
      id: upload-release-assetx64 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://github.com/naveen521kk/manim-build/releases/tag/v0.1.0
        asset_path: ./build.$PYVER.x64.exe
        asset_name: build.$PYVER.x64.exe
        asset_content_type: application/exe
    - name: Upload Release Asset x86
      id: upload-release-assetx86 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://github.com/naveen521kk/manim-build/releases/tag/v0.1.0
        asset_path: ./build.$PYVER.x64.exe
        asset_name: build.$PYVER.x64.exe
        asset_content_type: application/exe       
