name: Build Manim For Windows

on:
  push:
    branches: [ testing]

jobs:
  build_3_8_3:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-env
      uses: allenevans/set-env@v1.1.0
      with:
        PYVER: "3.8.3"
        PYDIR: Python38

    - name: Make choco Package
      run: |
        cd "Choco Package"
        cd "manim"
        choco pack
        choco install --no-progress manim -source "'.;https://chocolatey.org/api/v2/'" --ignore-checksums
        Start-Sleep -s 500
        echo "::set-env name=Path::$env:Path"
    - name: Test Generated Files
      run: |
        manim -h
        Invoke-WebRequest https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -O basic.py
        manim basic.py SquareToCircle
    - uses: actions/upload-artifact@v2
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
        
        
        
